# Generated by Django 4.0.1 on 2022-01-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productspecificationvalue_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecificationvalue',
            name='value',
            field=models.CharField(default='None', max_length=225),
        ),
    ]
