# Generated by Django 4.0.1 on 2022-02-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_options_remove_product_decimal_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecificationvalue',
            name='value',
            field=models.CharField(default=0.0, max_length=225),
        ),
    ]
